version: "3"
services: 
    portfolio:
        build: 
            context: ./src
            dockerfile: Dockerfile
        ports: 
            - "8889:80"
        restart: always
    database:
        image: mongo:latest
        ports: 
            - "27017:27017"
